In [2]:
# !pip install pandas

import pandas as pd

### 타이타닉 파일 확인

In [12]:
# titanic_train.csv 파일 읽어오기
titanic_df = pd.read_csv('data-files/titanic_train.csv')
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [9]:
# titanic_df 기본 정보 확인

# titanic_df 타입 확인
print('titanic 변수 type : ', type(titanic_df))

# titanic_df 크기 확인
print( 'DataFrame 크기 : ', titanic_df.shape )

# titanic_df 메타 데이터 확인
print( titanic_df.info() )

# titanic_df 데이터 분포도 확인
print( titanic_df.describe() )

titanic 변수 type :  <class 'pandas.core.frame.DataFrame'>
DataFrame 크기 :  (891, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.0000

In [10]:
# value_counts() 함수를 사용해 칼럼값의 유형과 건수 확인
value_counts = titanic_df['Pclass'].value_counts()
print( value_counts )

3    491
1    216
2    184
Name: Pclass, dtype: int64


In [13]:
# titanic_df['Pclass']의 데이터 타입 확인
titanic_pclass = titanic_df['Pclass']
print( type(titanic_pclass) )

# titanic_df['Pclass']의 ( 인덱스, 데이터값 ) 확인
print( titanic_pclass.head() )

<class 'pandas.core.series.Series'>
0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64


### ndarray, list, dictionary, DataFrame의 변환

In [3]:
# 여러 형태의 데이터들을 DataFrame으로 변환

import numpy as np

col_name1=['col']
list1 = [1, 2, 3]
array1 = np.array(list1)
print('array1 shape :', array1.shape)

# 리스트를 이용해 DataFrame 생성
df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame :\n', df_list1)

#넘파이 ndarray를 이용해 DataFrame 생성
df_array1 = pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame :\n', df_array1)

array1 shape : (3,)
1차원 리스트로 만든 DataFrame :
    col
0    1
1    2
2    3
1차원 ndarray로 만든 DataFrame :
    col
0    1
1    2
2    3


In [5]:
# 3개의 칼럼명이 필요함
col_name2 = ['col1', 'col2', 'col3']

# 2행 x 3행 형태의 리스트와 ndarray 생성한 뒤 이를 DataFrame으로 변환
list2 = [ [1, 2, 3], [11, 12, 13] ]

array2 = np.array(list2)
print('array2 shape :', array2.shape)

df_list2 = pd.DataFrame(list2, columns=col_name2)
print('2차원 list로 만든 DataFrame :\n', df_list2)

df_array2 = pd.DataFrame(array2, columns=col_name2)
print('2차원 ndarray로 만든 DataFrame :\n', df_array2)

array2 shape : (2, 3)
2차원 리스트로 만든 DataFrame :
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame :
    col1  col2  col3
0     1     2     3
1    11    12    13


In [6]:
# Key는 문자열 칼럼명으로 매핑, Value는 리스트 형(또는 ndarray) 칼럼 데이터로 매핑
dict = { 'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33] }
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame :\n', df_dict)

딕셔너리로 만든 DataFrame :
    col1  col2  col3
0     1     2     3
1    11    22    33


In [11]:
# DataFrame을 ndarray로 변환
array3 = df_dict.values
print('df_dict.values 타입 :', type(array3), 'df_dict.values shape :', array3.shape)
print(array3)

# DataFrame을 리스트로 변환
list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타입 :', type(list3))
print(list3)

# DataFrame을 딕셔너리로 변환
dict3 = df_dict.to_dict('list')
print('\ndf_dict.to_list() 타입 :', type(dict3))
print(dict3)

df_dict.values 타입 : <class 'numpy.ndarray'> df_dict.values shape : (2, 3)
[[ 1  2  3]
 [11 22 33]]
df_dict.values.tolist() 타입 : <class 'list'>
[[1, 2, 3], [11, 22, 33]]

df_dict.to_list() 타입 : <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


### DataFrame의 칼럼 데이터 세트 생성과 수정

In [14]:
# 'Age_0'라는 column 추가 후 일괄적으로 값 0을 할당
titanic_df['Age_0'] = 0
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0

In [15]:
# 기존의 컬럼 Series의 데이터를 이용해 'Age_by_10', 'Family_No' 두 개의 컬럼 추가
titanic_df['Age_by_10'] = titanic_df['Age'] * 10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      220.0   
1      0          PC 17599  71.2833   C85        C      0      380.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      260.0   

   Family_No  
0          2  
1          2  
2          1

In [17]:
# 기존 컬럼 일괄적으로 업데이트
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      420.0   
1      0          PC 17599  71.2833   C85        C      0      580.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      460.0   

   Family_No  
0          2  
1          2  
2          1

### DataFrame 데이터 삭제

In [18]:
# drop() 함수로 컬럼 제거
# axis=1 : 컬럼 방향 축, axis=0 : 로우 방향 축(default)
titanic_drop_df = titanic_df.drop('Age_0', axis=1)
titanic_drop_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_by_10  Family_No  
0      0         A/5 21171   7.2500   NaN        S      420.0          2  
1      0          PC 17599  71.2833   C85        C      580.0          2  
2      0  STON/O2. 3101282   7.9250   NaN        S      460.0          1

In [19]:
# drop() 함수로 컬럼 제거
# inplace=True : 자신의 데이터 삭제, inplace=False : 자신의 데이터는 삭제하지 않고 삭제된 결과 반환
drop_result = titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis=1, inplace=True)
print('inplace=True로 drop 후 반환된 값 :', drop_result)
titanic_df.head(3)

inplace=True로 drop 후 반환된 값 : None


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [20]:
# 출력창 설정
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 15)

# axis=1 : 컬럼 방향 축, axis=0 : 로우 방향 축(default)
print('#### before axis 0 drop ####')
print( titanic_df.head(3) )
titanic_df.drop([0, 1, 2], axis=0, inplace=True)

print('#### atfer axis 0 drop ####')
print( titanic_df.head(3) )

#### before axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
#### atfer axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q


### Index 객체

In [21]:
# 원본 파일 다시 로딩
titanic_df = pd.read_csv('data-files/titanic_train.csv')

# Index 객체 추출
indexes = titanic_df.index
print(indexes)

# Index 객체를 실제 값 array로 변환
print('Index 객체 array 값 :\n', indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index 객체 array 값 :
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 2

In [22]:
# 1차원 array의 Index 객체의 단일 값 반환 및 슬라이싱
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


In [23]:
# Series 객체에서 연산 함수를 적용할 때 Index는 연산에서 제외
series_fair = titanic_df['Fare']
print('Fair Series max 값 :', series_fair.max())
print('Fair Series sum 값 :', series_fair.sum())
print('sum() Fair Series :', sum(series_fair))
print('Fair Series + 3 :\n', (series_fair + 3).head(3))

Fair Series max 값 : 512.3292
Fair Series sum 값 : 28693.9493
sum() Fair Series : 28693.949299999967
Fair Series + 3 :
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64
